package events.serverevents.nluser;

public enum SignUpResults {
    NAME_IS_EMPTY,
    INVALID_NAME,
    LASTNAME_IS_EMPTY,
    INVALID_LASTNAME,
    USERNAME_IS_EMPTY,
    INVALID_USERNAME,
    USERNAME_IS_TAKEN,
    PASSWORD_IS_EMPTY,
    INVALID_PASSWORD,
    RETYPED_PASSWORD_IS_EMPTY,
    PASSWORDS_ARE_NOT_SAME,
    BIRTHDATE_IN_EMPTY,
    EMAIL_IS_EMPTY,
    EMAIL_IS_TAKEN,
    INVALID_EMAIL,
    PHONENUMBER_IS_EMPTY,
    INVALID_PHONENUMBER,
    NO_PROBLEM
}
